backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/info" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagen 1", name: "imageOne", widget: "image", required: false}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Ingredientes", name: "body", widget: "markdown"}
